# Configs for ozanerhansha.github.io

title: "Ozaner's Notes"
name: "ozanerhansha.github.io"
# email: ozanerhansha@gmail.com
url: "https://ozanerhansha.github.io"
repository: "ozanerhansha/ozanerhansha.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  My notes on math, computer science, philosophy, personal projects, and more.

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Ozaner Hansha"
  avatar : "/assets/images/bio.gif"
  bio    : "My notes on math, computer science, philosophy, personal projects, and more."
  # location: "Seattle, WA"
  github : ozanerhansha
  # linkedin: ozanerhansha
  # email  : ozanerhansha@gmail.com
  medium : ozanerhansha


# # comments by disqus
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "placeholder"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-111962015-1"


# pagination for blog page
permalink: /:title/
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Overview"
      read_time: false
      comments: false
      related: true
      tags: true
      # categories: true
  # coursework
  - scope:
      path: ""
      type: coursework
    values:
      author_profile: false
      toc: true
      toc_label: "Overview"
      excerpt: ""
      sidebar:
        nav: "coursework"
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

tag_archive:
  type: liquid
  path: /tags/

# collections
collections:
  portfolio:
    output: true
  coursework:
    output: true

